VARIANT_INDEX_ARR=(0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 28 29)
echo "    [$(c_green 0)]     GNOME (with NVIDIA 390.* driver)"
echo "    [$(c_green 1)]     Plasma (a.k.a. KDE) (with NVIDIA 390.* driver)"
echo "    [$(c_green 2)]     BuildKit"
echo "    [$(c_green 3)]     MATE (with NVIDIA 340.* driver)"
echo "    [$(c_green 4)]     Plasma (a.k.a. KDE) (with NVIDIA 340.* driver)"
echo "    [$(c_green 5)]     Cinnamon (with NVIDIA 340.* driver)"
echo "    [$(c_green 6)]     GNOME (with NVIDIA 340.* driver)"
echo "    [$(c_green 7)]     LXDE (with NVIDIA mainline driver)"
echo "    [$(c_green 8)]     Xfce"
echo "    [$(c_green 9)]     Xfce (with NVIDIA 340.* driver)"
echo "    [$(c_green 10)]    MATE (with NVIDIA mainline driver)"
echo "    [$(c_green 11)]    Cinnamon (with NVIDIA 390.* driver)"
echo "    [$(c_green 12)]    Cinnamon (with NVIDIA mainline driver)"
echo "    [$(c_green 13)]    Plasma (a.k.a. KDE)"
echo "    [$(c_green 14)]    GNOME (with NVIDIA mainline driver)"
echo "    [$(c_green 15)]    Xfce (with NVIDIA mainline driver)"
echo "    [$(c_green 16)]    Cinnamon"
echo "    [$(c_green 17)]    Base"
echo "    [$(c_green 18)]    LXDE (with NVIDIA 390.* driver)"
echo "    [$(c_green 19)]    LXDE (with NVIDIA 340.* driver)"
echo "    [$(c_green 20)]    MATE (with NVIDIA 390.* driver)"
echo "    [$(c_green 21)]    Plasma (a.k.a. KDE) (with NVIDIA mainline driver)"
echo "    [$(c_green 22)]    LXDE"
echo "    [$(c_green 23)]    Xfce (with NVIDIA 390.* driver)"
echo "    [$(c_green 24)]    MATE"
echo "    [$(c_green 25)]    GNOME"
echo "    [$(c_green 26)]    BuildKit (Retro)"
echo "    [$(c_green 28)]    Base (Retro)"
echo "    [$(c_green 29)]    X11 (Retro)"
NUM_MAX_ALLOW=29